// Code generated by ent, DO NOT EDIT.

package signuptoken

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the signuptoken type in the database.
	Label = "signup_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCsrfToken holds the string denoting the csrf_token field in the database.
	FieldCsrfToken = "csrf_token"
	// FieldValidationToken holds the string denoting the validation_token field in the database.
	FieldValidationToken = "validation_token"
	// FieldExpiry holds the string denoting the expiry field in the database.
	FieldExpiry = "expiry"
	// Table holds the table name of the signuptoken in the database.
	Table = "signup_tokens"
)

// Columns holds all SQL columns for signuptoken fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldCsrfToken,
	FieldValidationToken,
	FieldExpiry,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// CsrfTokenValidator is a validator for the "csrf_token" field. It is called by the builders before save.
	CsrfTokenValidator func(string) error
	// ValidationTokenValidator is a validator for the "validation_token" field. It is called by the builders before save.
	ValidationTokenValidator func(string) error
)

// OrderOption defines the ordering options for the SignupToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByCsrfToken orders the results by the csrf_token field.
func ByCsrfToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCsrfToken, opts...).ToFunc()
}

// ByValidationToken orders the results by the validation_token field.
func ByValidationToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidationToken, opts...).ToFunc()
}

// ByExpiry orders the results by the expiry field.
func ByExpiry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiry, opts...).ToFunc()
}
