// Code generated by ent, DO NOT EDIT.

package signuptoken

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dexidp/dex/storage/ent/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldEmail, v))
}

// CsrfToken applies equality check predicate on the "csrf_token" field. It's identical to CsrfTokenEQ.
func CsrfToken(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldCsrfToken, v))
}

// ValidationToken applies equality check predicate on the "validation_token" field. It's identical to ValidationTokenEQ.
func ValidationToken(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldValidationToken, v))
}

// Expiry applies equality check predicate on the "expiry" field. It's identical to ExpiryEQ.
func Expiry(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldExpiry, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContainsFold(FieldEmail, v))
}

// CsrfTokenEQ applies the EQ predicate on the "csrf_token" field.
func CsrfTokenEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldCsrfToken, v))
}

// CsrfTokenNEQ applies the NEQ predicate on the "csrf_token" field.
func CsrfTokenNEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNEQ(FieldCsrfToken, v))
}

// CsrfTokenIn applies the In predicate on the "csrf_token" field.
func CsrfTokenIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldIn(FieldCsrfToken, vs...))
}

// CsrfTokenNotIn applies the NotIn predicate on the "csrf_token" field.
func CsrfTokenNotIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNotIn(FieldCsrfToken, vs...))
}

// CsrfTokenGT applies the GT predicate on the "csrf_token" field.
func CsrfTokenGT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGT(FieldCsrfToken, v))
}

// CsrfTokenGTE applies the GTE predicate on the "csrf_token" field.
func CsrfTokenGTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGTE(FieldCsrfToken, v))
}

// CsrfTokenLT applies the LT predicate on the "csrf_token" field.
func CsrfTokenLT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLT(FieldCsrfToken, v))
}

// CsrfTokenLTE applies the LTE predicate on the "csrf_token" field.
func CsrfTokenLTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLTE(FieldCsrfToken, v))
}

// CsrfTokenContains applies the Contains predicate on the "csrf_token" field.
func CsrfTokenContains(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContains(FieldCsrfToken, v))
}

// CsrfTokenHasPrefix applies the HasPrefix predicate on the "csrf_token" field.
func CsrfTokenHasPrefix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasPrefix(FieldCsrfToken, v))
}

// CsrfTokenHasSuffix applies the HasSuffix predicate on the "csrf_token" field.
func CsrfTokenHasSuffix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasSuffix(FieldCsrfToken, v))
}

// CsrfTokenEqualFold applies the EqualFold predicate on the "csrf_token" field.
func CsrfTokenEqualFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEqualFold(FieldCsrfToken, v))
}

// CsrfTokenContainsFold applies the ContainsFold predicate on the "csrf_token" field.
func CsrfTokenContainsFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContainsFold(FieldCsrfToken, v))
}

// ValidationTokenEQ applies the EQ predicate on the "validation_token" field.
func ValidationTokenEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldValidationToken, v))
}

// ValidationTokenNEQ applies the NEQ predicate on the "validation_token" field.
func ValidationTokenNEQ(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNEQ(FieldValidationToken, v))
}

// ValidationTokenIn applies the In predicate on the "validation_token" field.
func ValidationTokenIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldIn(FieldValidationToken, vs...))
}

// ValidationTokenNotIn applies the NotIn predicate on the "validation_token" field.
func ValidationTokenNotIn(vs ...string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNotIn(FieldValidationToken, vs...))
}

// ValidationTokenGT applies the GT predicate on the "validation_token" field.
func ValidationTokenGT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGT(FieldValidationToken, v))
}

// ValidationTokenGTE applies the GTE predicate on the "validation_token" field.
func ValidationTokenGTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGTE(FieldValidationToken, v))
}

// ValidationTokenLT applies the LT predicate on the "validation_token" field.
func ValidationTokenLT(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLT(FieldValidationToken, v))
}

// ValidationTokenLTE applies the LTE predicate on the "validation_token" field.
func ValidationTokenLTE(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLTE(FieldValidationToken, v))
}

// ValidationTokenContains applies the Contains predicate on the "validation_token" field.
func ValidationTokenContains(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContains(FieldValidationToken, v))
}

// ValidationTokenHasPrefix applies the HasPrefix predicate on the "validation_token" field.
func ValidationTokenHasPrefix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasPrefix(FieldValidationToken, v))
}

// ValidationTokenHasSuffix applies the HasSuffix predicate on the "validation_token" field.
func ValidationTokenHasSuffix(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldHasSuffix(FieldValidationToken, v))
}

// ValidationTokenEqualFold applies the EqualFold predicate on the "validation_token" field.
func ValidationTokenEqualFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEqualFold(FieldValidationToken, v))
}

// ValidationTokenContainsFold applies the ContainsFold predicate on the "validation_token" field.
func ValidationTokenContainsFold(v string) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldContainsFold(FieldValidationToken, v))
}

// ExpiryEQ applies the EQ predicate on the "expiry" field.
func ExpiryEQ(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldEQ(FieldExpiry, v))
}

// ExpiryNEQ applies the NEQ predicate on the "expiry" field.
func ExpiryNEQ(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNEQ(FieldExpiry, v))
}

// ExpiryIn applies the In predicate on the "expiry" field.
func ExpiryIn(vs ...time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldIn(FieldExpiry, vs...))
}

// ExpiryNotIn applies the NotIn predicate on the "expiry" field.
func ExpiryNotIn(vs ...time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldNotIn(FieldExpiry, vs...))
}

// ExpiryGT applies the GT predicate on the "expiry" field.
func ExpiryGT(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGT(FieldExpiry, v))
}

// ExpiryGTE applies the GTE predicate on the "expiry" field.
func ExpiryGTE(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldGTE(FieldExpiry, v))
}

// ExpiryLT applies the LT predicate on the "expiry" field.
func ExpiryLT(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLT(FieldExpiry, v))
}

// ExpiryLTE applies the LTE predicate on the "expiry" field.
func ExpiryLTE(v time.Time) predicate.SignupToken {
	return predicate.SignupToken(sql.FieldLTE(FieldExpiry, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SignupToken) predicate.SignupToken {
	return predicate.SignupToken(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SignupToken) predicate.SignupToken {
	return predicate.SignupToken(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SignupToken) predicate.SignupToken {
	return predicate.SignupToken(sql.NotPredicates(p))
}
