// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/authcode"
)

// AuthCodeCreate is the builder for creating a AuthCode entity.
type AuthCodeCreate struct {
	config
	mutation *AuthCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetClientID sets the "client_id" field.
func (_c *AuthCodeCreate) SetClientID(v string) *AuthCodeCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *AuthCodeCreate) SetScopes(v []string) *AuthCodeCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *AuthCodeCreate) SetNonce(v string) *AuthCodeCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *AuthCodeCreate) SetRedirectURI(v string) *AuthCodeCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetClaimsUserID sets the "claims_user_id" field.
func (_c *AuthCodeCreate) SetClaimsUserID(v string) *AuthCodeCreate {
	_c.mutation.SetClaimsUserID(v)
	return _c
}

// SetClaimsUsername sets the "claims_username" field.
func (_c *AuthCodeCreate) SetClaimsUsername(v string) *AuthCodeCreate {
	_c.mutation.SetClaimsUsername(v)
	return _c
}

// SetClaimsEmail sets the "claims_email" field.
func (_c *AuthCodeCreate) SetClaimsEmail(v string) *AuthCodeCreate {
	_c.mutation.SetClaimsEmail(v)
	return _c
}

// SetClaimsEmailVerified sets the "claims_email_verified" field.
func (_c *AuthCodeCreate) SetClaimsEmailVerified(v bool) *AuthCodeCreate {
	_c.mutation.SetClaimsEmailVerified(v)
	return _c
}

// SetClaimsGroups sets the "claims_groups" field.
func (_c *AuthCodeCreate) SetClaimsGroups(v []string) *AuthCodeCreate {
	_c.mutation.SetClaimsGroups(v)
	return _c
}

// SetClaimsPreferredUsername sets the "claims_preferred_username" field.
func (_c *AuthCodeCreate) SetClaimsPreferredUsername(v string) *AuthCodeCreate {
	_c.mutation.SetClaimsPreferredUsername(v)
	return _c
}

// SetNillableClaimsPreferredUsername sets the "claims_preferred_username" field if the given value is not nil.
func (_c *AuthCodeCreate) SetNillableClaimsPreferredUsername(v *string) *AuthCodeCreate {
	if v != nil {
		_c.SetClaimsPreferredUsername(*v)
	}
	return _c
}

// SetConnectorID sets the "connector_id" field.
func (_c *AuthCodeCreate) SetConnectorID(v string) *AuthCodeCreate {
	_c.mutation.SetConnectorID(v)
	return _c
}

// SetConnectorData sets the "connector_data" field.
func (_c *AuthCodeCreate) SetConnectorData(v []byte) *AuthCodeCreate {
	_c.mutation.SetConnectorData(v)
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *AuthCodeCreate) SetExpiry(v time.Time) *AuthCodeCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *AuthCodeCreate) SetCodeChallenge(v string) *AuthCodeCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_c *AuthCodeCreate) SetNillableCodeChallenge(v *string) *AuthCodeCreate {
	if v != nil {
		_c.SetCodeChallenge(*v)
	}
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *AuthCodeCreate) SetCodeChallengeMethod(v string) *AuthCodeCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *AuthCodeCreate) SetNillableCodeChallengeMethod(v *string) *AuthCodeCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthCodeCreate) SetID(v string) *AuthCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthCodeMutation object of the builder.
func (_c *AuthCodeCreate) Mutation() *AuthCodeMutation {
	return _c.mutation
}

// Save creates the AuthCode in the database.
func (_c *AuthCodeCreate) Save(ctx context.Context) (*AuthCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthCodeCreate) SaveX(ctx context.Context) *AuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthCodeCreate) defaults() {
	if _, ok := _c.mutation.ClaimsPreferredUsername(); !ok {
		v := authcode.DefaultClaimsPreferredUsername
		_c.mutation.SetClaimsPreferredUsername(v)
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		v := authcode.DefaultCodeChallenge
		_c.mutation.SetCodeChallenge(v)
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := authcode.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthCodeCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`db: missing required field "AuthCode.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := authcode.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`db: validator failed for field "AuthCode.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nonce(); !ok {
		return &ValidationError{Name: "nonce", err: errors.New(`db: missing required field "AuthCode.nonce"`)}
	}
	if v, ok := _c.mutation.Nonce(); ok {
		if err := authcode.NonceValidator(v); err != nil {
			return &ValidationError{Name: "nonce", err: fmt.Errorf(`db: validator failed for field "AuthCode.nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`db: missing required field "AuthCode.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := authcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`db: validator failed for field "AuthCode.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClaimsUserID(); !ok {
		return &ValidationError{Name: "claims_user_id", err: errors.New(`db: missing required field "AuthCode.claims_user_id"`)}
	}
	if v, ok := _c.mutation.ClaimsUserID(); ok {
		if err := authcode.ClaimsUserIDValidator(v); err != nil {
			return &ValidationError{Name: "claims_user_id", err: fmt.Errorf(`db: validator failed for field "AuthCode.claims_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClaimsUsername(); !ok {
		return &ValidationError{Name: "claims_username", err: errors.New(`db: missing required field "AuthCode.claims_username"`)}
	}
	if v, ok := _c.mutation.ClaimsUsername(); ok {
		if err := authcode.ClaimsUsernameValidator(v); err != nil {
			return &ValidationError{Name: "claims_username", err: fmt.Errorf(`db: validator failed for field "AuthCode.claims_username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClaimsEmail(); !ok {
		return &ValidationError{Name: "claims_email", err: errors.New(`db: missing required field "AuthCode.claims_email"`)}
	}
	if v, ok := _c.mutation.ClaimsEmail(); ok {
		if err := authcode.ClaimsEmailValidator(v); err != nil {
			return &ValidationError{Name: "claims_email", err: fmt.Errorf(`db: validator failed for field "AuthCode.claims_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClaimsEmailVerified(); !ok {
		return &ValidationError{Name: "claims_email_verified", err: errors.New(`db: missing required field "AuthCode.claims_email_verified"`)}
	}
	if _, ok := _c.mutation.ClaimsPreferredUsername(); !ok {
		return &ValidationError{Name: "claims_preferred_username", err: errors.New(`db: missing required field "AuthCode.claims_preferred_username"`)}
	}
	if _, ok := _c.mutation.ConnectorID(); !ok {
		return &ValidationError{Name: "connector_id", err: errors.New(`db: missing required field "AuthCode.connector_id"`)}
	}
	if v, ok := _c.mutation.ConnectorID(); ok {
		if err := authcode.ConnectorIDValidator(v); err != nil {
			return &ValidationError{Name: "connector_id", err: fmt.Errorf(`db: validator failed for field "AuthCode.connector_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`db: missing required field "AuthCode.expiry"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`db: missing required field "AuthCode.code_challenge"`)}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`db: missing required field "AuthCode.code_challenge_method"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := authcode.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`db: validator failed for field "AuthCode.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AuthCodeCreate) sqlSave(ctx context.Context) (*AuthCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthCode.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthCodeCreate) createSpec() (*AuthCode, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authcode.Table, sqlgraph.NewFieldSpec(authcode.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(authcode.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(authcode.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(authcode.FieldNonce, field.TypeString, value)
		_node.Nonce = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(authcode.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.ClaimsUserID(); ok {
		_spec.SetField(authcode.FieldClaimsUserID, field.TypeString, value)
		_node.ClaimsUserID = value
	}
	if value, ok := _c.mutation.ClaimsUsername(); ok {
		_spec.SetField(authcode.FieldClaimsUsername, field.TypeString, value)
		_node.ClaimsUsername = value
	}
	if value, ok := _c.mutation.ClaimsEmail(); ok {
		_spec.SetField(authcode.FieldClaimsEmail, field.TypeString, value)
		_node.ClaimsEmail = value
	}
	if value, ok := _c.mutation.ClaimsEmailVerified(); ok {
		_spec.SetField(authcode.FieldClaimsEmailVerified, field.TypeBool, value)
		_node.ClaimsEmailVerified = value
	}
	if value, ok := _c.mutation.ClaimsGroups(); ok {
		_spec.SetField(authcode.FieldClaimsGroups, field.TypeJSON, value)
		_node.ClaimsGroups = value
	}
	if value, ok := _c.mutation.ClaimsPreferredUsername(); ok {
		_spec.SetField(authcode.FieldClaimsPreferredUsername, field.TypeString, value)
		_node.ClaimsPreferredUsername = value
	}
	if value, ok := _c.mutation.ConnectorID(); ok {
		_spec.SetField(authcode.FieldConnectorID, field.TypeString, value)
		_node.ConnectorID = value
	}
	if value, ok := _c.mutation.ConnectorData(); ok {
		_spec.SetField(authcode.FieldConnectorData, field.TypeBytes, value)
		_node.ConnectorData = &value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(authcode.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(authcode.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(authcode.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthCode.Create().
//		SetClientID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthCodeUpsert) {
//			SetClientID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthCodeCreate) OnConflict(opts ...sql.ConflictOption) *AuthCodeUpsertOne {
	_c.conflict = opts
	return &AuthCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthCodeCreate) OnConflictColumns(columns ...string) *AuthCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthCodeUpsertOne{
		create: _c,
	}
}

type (
	// AuthCodeUpsertOne is the builder for "upsert"-ing
	//  one AuthCode node.
	AuthCodeUpsertOne struct {
		create *AuthCodeCreate
	}

	// AuthCodeUpsert is the "OnConflict" setter.
	AuthCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetClientID sets the "client_id" field.
func (u *AuthCodeUpsert) SetClientID(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClientID() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClientID)
	return u
}

// SetScopes sets the "scopes" field.
func (u *AuthCodeUpsert) SetScopes(v []string) *AuthCodeUpsert {
	u.Set(authcode.FieldScopes, v)
	return u
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateScopes() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldScopes)
	return u
}

// ClearScopes clears the value of the "scopes" field.
func (u *AuthCodeUpsert) ClearScopes() *AuthCodeUpsert {
	u.SetNull(authcode.FieldScopes)
	return u
}

// SetNonce sets the "nonce" field.
func (u *AuthCodeUpsert) SetNonce(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldNonce, v)
	return u
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateNonce() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldNonce)
	return u
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *AuthCodeUpsert) SetRedirectURI(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldRedirectURI, v)
	return u
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateRedirectURI() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldRedirectURI)
	return u
}

// SetClaimsUserID sets the "claims_user_id" field.
func (u *AuthCodeUpsert) SetClaimsUserID(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsUserID, v)
	return u
}

// UpdateClaimsUserID sets the "claims_user_id" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsUserID() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsUserID)
	return u
}

// SetClaimsUsername sets the "claims_username" field.
func (u *AuthCodeUpsert) SetClaimsUsername(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsUsername, v)
	return u
}

// UpdateClaimsUsername sets the "claims_username" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsUsername() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsUsername)
	return u
}

// SetClaimsEmail sets the "claims_email" field.
func (u *AuthCodeUpsert) SetClaimsEmail(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsEmail, v)
	return u
}

// UpdateClaimsEmail sets the "claims_email" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsEmail() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsEmail)
	return u
}

// SetClaimsEmailVerified sets the "claims_email_verified" field.
func (u *AuthCodeUpsert) SetClaimsEmailVerified(v bool) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsEmailVerified, v)
	return u
}

// UpdateClaimsEmailVerified sets the "claims_email_verified" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsEmailVerified() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsEmailVerified)
	return u
}

// SetClaimsGroups sets the "claims_groups" field.
func (u *AuthCodeUpsert) SetClaimsGroups(v []string) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsGroups, v)
	return u
}

// UpdateClaimsGroups sets the "claims_groups" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsGroups() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsGroups)
	return u
}

// ClearClaimsGroups clears the value of the "claims_groups" field.
func (u *AuthCodeUpsert) ClearClaimsGroups() *AuthCodeUpsert {
	u.SetNull(authcode.FieldClaimsGroups)
	return u
}

// SetClaimsPreferredUsername sets the "claims_preferred_username" field.
func (u *AuthCodeUpsert) SetClaimsPreferredUsername(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldClaimsPreferredUsername, v)
	return u
}

// UpdateClaimsPreferredUsername sets the "claims_preferred_username" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateClaimsPreferredUsername() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldClaimsPreferredUsername)
	return u
}

// SetConnectorID sets the "connector_id" field.
func (u *AuthCodeUpsert) SetConnectorID(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldConnectorID, v)
	return u
}

// UpdateConnectorID sets the "connector_id" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateConnectorID() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldConnectorID)
	return u
}

// SetConnectorData sets the "connector_data" field.
func (u *AuthCodeUpsert) SetConnectorData(v []byte) *AuthCodeUpsert {
	u.Set(authcode.FieldConnectorData, v)
	return u
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateConnectorData() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldConnectorData)
	return u
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *AuthCodeUpsert) ClearConnectorData() *AuthCodeUpsert {
	u.SetNull(authcode.FieldConnectorData)
	return u
}

// SetExpiry sets the "expiry" field.
func (u *AuthCodeUpsert) SetExpiry(v time.Time) *AuthCodeUpsert {
	u.Set(authcode.FieldExpiry, v)
	return u
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateExpiry() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldExpiry)
	return u
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *AuthCodeUpsert) SetCodeChallenge(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldCodeChallenge, v)
	return u
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateCodeChallenge() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldCodeChallenge)
	return u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *AuthCodeUpsert) SetCodeChallengeMethod(v string) *AuthCodeUpsert {
	u.Set(authcode.FieldCodeChallengeMethod, v)
	return u
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *AuthCodeUpsert) UpdateCodeChallengeMethod() *AuthCodeUpsert {
	u.SetExcluded(authcode.FieldCodeChallengeMethod)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthCodeUpsertOne) UpdateNewValues() *AuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authcode.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthCodeUpsertOne) Ignore() *AuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthCodeUpsertOne) DoNothing() *AuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthCodeCreate.OnConflict
// documentation for more info.
func (u *AuthCodeUpsertOne) Update(set func(*AuthCodeUpsert)) *AuthCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClientID sets the "client_id" field.
func (u *AuthCodeUpsertOne) SetClientID(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClientID() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *AuthCodeUpsertOne) SetScopes(v []string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateScopes() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// ClearScopes clears the value of the "scopes" field.
func (u *AuthCodeUpsertOne) ClearScopes() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearScopes()
	})
}

// SetNonce sets the "nonce" field.
func (u *AuthCodeUpsertOne) SetNonce(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateNonce() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateNonce()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *AuthCodeUpsertOne) SetRedirectURI(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateRedirectURI() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetClaimsUserID sets the "claims_user_id" field.
func (u *AuthCodeUpsertOne) SetClaimsUserID(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsUserID(v)
	})
}

// UpdateClaimsUserID sets the "claims_user_id" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsUserID() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsUserID()
	})
}

// SetClaimsUsername sets the "claims_username" field.
func (u *AuthCodeUpsertOne) SetClaimsUsername(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsUsername(v)
	})
}

// UpdateClaimsUsername sets the "claims_username" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsUsername() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsUsername()
	})
}

// SetClaimsEmail sets the "claims_email" field.
func (u *AuthCodeUpsertOne) SetClaimsEmail(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsEmail(v)
	})
}

// UpdateClaimsEmail sets the "claims_email" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsEmail() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsEmail()
	})
}

// SetClaimsEmailVerified sets the "claims_email_verified" field.
func (u *AuthCodeUpsertOne) SetClaimsEmailVerified(v bool) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsEmailVerified(v)
	})
}

// UpdateClaimsEmailVerified sets the "claims_email_verified" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsEmailVerified() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsEmailVerified()
	})
}

// SetClaimsGroups sets the "claims_groups" field.
func (u *AuthCodeUpsertOne) SetClaimsGroups(v []string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsGroups(v)
	})
}

// UpdateClaimsGroups sets the "claims_groups" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsGroups() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsGroups()
	})
}

// ClearClaimsGroups clears the value of the "claims_groups" field.
func (u *AuthCodeUpsertOne) ClearClaimsGroups() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearClaimsGroups()
	})
}

// SetClaimsPreferredUsername sets the "claims_preferred_username" field.
func (u *AuthCodeUpsertOne) SetClaimsPreferredUsername(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsPreferredUsername(v)
	})
}

// UpdateClaimsPreferredUsername sets the "claims_preferred_username" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateClaimsPreferredUsername() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsPreferredUsername()
	})
}

// SetConnectorID sets the "connector_id" field.
func (u *AuthCodeUpsertOne) SetConnectorID(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetConnectorID(v)
	})
}

// UpdateConnectorID sets the "connector_id" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateConnectorID() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateConnectorID()
	})
}

// SetConnectorData sets the "connector_data" field.
func (u *AuthCodeUpsertOne) SetConnectorData(v []byte) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetConnectorData(v)
	})
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateConnectorData() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateConnectorData()
	})
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *AuthCodeUpsertOne) ClearConnectorData() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearConnectorData()
	})
}

// SetExpiry sets the "expiry" field.
func (u *AuthCodeUpsertOne) SetExpiry(v time.Time) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetExpiry(v)
	})
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateExpiry() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateExpiry()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *AuthCodeUpsertOne) SetCodeChallenge(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateCodeChallenge() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *AuthCodeUpsertOne) SetCodeChallengeMethod(v string) *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *AuthCodeUpsertOne) UpdateCodeChallengeMethod() *AuthCodeUpsertOne {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// Exec executes the query.
func (u *AuthCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for AuthCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthCodeUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: AuthCodeUpsertOne.ID is not supported by MySQL driver. Use AuthCodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthCodeUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthCodeCreateBulk is the builder for creating many AuthCode entities in bulk.
type AuthCodeCreateBulk struct {
	config
	err      error
	builders []*AuthCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthCode entities in the database.
func (_c *AuthCodeCreateBulk) Save(ctx context.Context) ([]*AuthCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthCodeCreateBulk) SaveX(ctx context.Context) []*AuthCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthCodeUpsert) {
//			SetClientID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthCodeUpsertBulk {
	_c.conflict = opts
	return &AuthCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthCodeCreateBulk) OnConflictColumns(columns ...string) *AuthCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthCodeUpsertBulk{
		create: _c,
	}
}

// AuthCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthCode nodes.
type AuthCodeUpsertBulk struct {
	create *AuthCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthCodeUpsertBulk) UpdateNewValues() *AuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authcode.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthCodeUpsertBulk) Ignore() *AuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthCodeUpsertBulk) DoNothing() *AuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthCodeCreateBulk.OnConflict
// documentation for more info.
func (u *AuthCodeUpsertBulk) Update(set func(*AuthCodeUpsert)) *AuthCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetClientID sets the "client_id" field.
func (u *AuthCodeUpsertBulk) SetClientID(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClientID() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClientID()
	})
}

// SetScopes sets the "scopes" field.
func (u *AuthCodeUpsertBulk) SetScopes(v []string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetScopes(v)
	})
}

// UpdateScopes sets the "scopes" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateScopes() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateScopes()
	})
}

// ClearScopes clears the value of the "scopes" field.
func (u *AuthCodeUpsertBulk) ClearScopes() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearScopes()
	})
}

// SetNonce sets the "nonce" field.
func (u *AuthCodeUpsertBulk) SetNonce(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetNonce(v)
	})
}

// UpdateNonce sets the "nonce" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateNonce() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateNonce()
	})
}

// SetRedirectURI sets the "redirect_uri" field.
func (u *AuthCodeUpsertBulk) SetRedirectURI(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetRedirectURI(v)
	})
}

// UpdateRedirectURI sets the "redirect_uri" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateRedirectURI() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateRedirectURI()
	})
}

// SetClaimsUserID sets the "claims_user_id" field.
func (u *AuthCodeUpsertBulk) SetClaimsUserID(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsUserID(v)
	})
}

// UpdateClaimsUserID sets the "claims_user_id" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsUserID() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsUserID()
	})
}

// SetClaimsUsername sets the "claims_username" field.
func (u *AuthCodeUpsertBulk) SetClaimsUsername(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsUsername(v)
	})
}

// UpdateClaimsUsername sets the "claims_username" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsUsername() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsUsername()
	})
}

// SetClaimsEmail sets the "claims_email" field.
func (u *AuthCodeUpsertBulk) SetClaimsEmail(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsEmail(v)
	})
}

// UpdateClaimsEmail sets the "claims_email" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsEmail() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsEmail()
	})
}

// SetClaimsEmailVerified sets the "claims_email_verified" field.
func (u *AuthCodeUpsertBulk) SetClaimsEmailVerified(v bool) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsEmailVerified(v)
	})
}

// UpdateClaimsEmailVerified sets the "claims_email_verified" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsEmailVerified() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsEmailVerified()
	})
}

// SetClaimsGroups sets the "claims_groups" field.
func (u *AuthCodeUpsertBulk) SetClaimsGroups(v []string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsGroups(v)
	})
}

// UpdateClaimsGroups sets the "claims_groups" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsGroups() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsGroups()
	})
}

// ClearClaimsGroups clears the value of the "claims_groups" field.
func (u *AuthCodeUpsertBulk) ClearClaimsGroups() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearClaimsGroups()
	})
}

// SetClaimsPreferredUsername sets the "claims_preferred_username" field.
func (u *AuthCodeUpsertBulk) SetClaimsPreferredUsername(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetClaimsPreferredUsername(v)
	})
}

// UpdateClaimsPreferredUsername sets the "claims_preferred_username" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateClaimsPreferredUsername() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateClaimsPreferredUsername()
	})
}

// SetConnectorID sets the "connector_id" field.
func (u *AuthCodeUpsertBulk) SetConnectorID(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetConnectorID(v)
	})
}

// UpdateConnectorID sets the "connector_id" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateConnectorID() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateConnectorID()
	})
}

// SetConnectorData sets the "connector_data" field.
func (u *AuthCodeUpsertBulk) SetConnectorData(v []byte) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetConnectorData(v)
	})
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateConnectorData() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateConnectorData()
	})
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *AuthCodeUpsertBulk) ClearConnectorData() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.ClearConnectorData()
	})
}

// SetExpiry sets the "expiry" field.
func (u *AuthCodeUpsertBulk) SetExpiry(v time.Time) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetExpiry(v)
	})
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateExpiry() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateExpiry()
	})
}

// SetCodeChallenge sets the "code_challenge" field.
func (u *AuthCodeUpsertBulk) SetCodeChallenge(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetCodeChallenge(v)
	})
}

// UpdateCodeChallenge sets the "code_challenge" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateCodeChallenge() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateCodeChallenge()
	})
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (u *AuthCodeUpsertBulk) SetCodeChallengeMethod(v string) *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.SetCodeChallengeMethod(v)
	})
}

// UpdateCodeChallengeMethod sets the "code_challenge_method" field to the value that was provided on create.
func (u *AuthCodeUpsertBulk) UpdateCodeChallengeMethod() *AuthCodeUpsertBulk {
	return u.Update(func(s *AuthCodeUpsert) {
		s.UpdateCodeChallengeMethod()
	})
}

// Exec executes the query.
func (u *AuthCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the AuthCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for AuthCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
