// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/oauth2client"
)

// OAuth2ClientCreate is the builder for creating a OAuth2Client entity.
type OAuth2ClientCreate struct {
	config
	mutation *OAuth2ClientMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSecret sets the "secret" field.
func (_c *OAuth2ClientCreate) SetSecret(v string) *OAuth2ClientCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetRedirectUris sets the "redirect_uris" field.
func (_c *OAuth2ClientCreate) SetRedirectUris(v []string) *OAuth2ClientCreate {
	_c.mutation.SetRedirectUris(v)
	return _c
}

// SetTrustedPeers sets the "trusted_peers" field.
func (_c *OAuth2ClientCreate) SetTrustedPeers(v []string) *OAuth2ClientCreate {
	_c.mutation.SetTrustedPeers(v)
	return _c
}

// SetPublic sets the "public" field.
func (_c *OAuth2ClientCreate) SetPublic(v bool) *OAuth2ClientCreate {
	_c.mutation.SetPublic(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OAuth2ClientCreate) SetName(v string) *OAuth2ClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *OAuth2ClientCreate) SetLogoURL(v string) *OAuth2ClientCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OAuth2ClientCreate) SetID(v string) *OAuth2ClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuth2ClientMutation object of the builder.
func (_c *OAuth2ClientCreate) Mutation() *OAuth2ClientMutation {
	return _c.mutation
}

// Save creates the OAuth2Client in the database.
func (_c *OAuth2ClientCreate) Save(ctx context.Context) (*OAuth2Client, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuth2ClientCreate) SaveX(ctx context.Context) *OAuth2Client {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuth2ClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuth2ClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuth2ClientCreate) check() error {
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`db: missing required field "OAuth2Client.secret"`)}
	}
	if v, ok := _c.mutation.Secret(); ok {
		if err := oauth2client.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`db: validator failed for field "OAuth2Client.secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Public(); !ok {
		return &ValidationError{Name: "public", err: errors.New(`db: missing required field "OAuth2Client.public"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "OAuth2Client.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauth2client.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "OAuth2Client.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LogoURL(); !ok {
		return &ValidationError{Name: "logo_url", err: errors.New(`db: missing required field "OAuth2Client.logo_url"`)}
	}
	if v, ok := _c.mutation.LogoURL(); ok {
		if err := oauth2client.LogoURLValidator(v); err != nil {
			return &ValidationError{Name: "logo_url", err: fmt.Errorf(`db: validator failed for field "OAuth2Client.logo_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := oauth2client.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`db: validator failed for field "OAuth2Client.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuth2ClientCreate) sqlSave(ctx context.Context) (*OAuth2Client, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OAuth2Client.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuth2ClientCreate) createSpec() (*OAuth2Client, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuth2Client{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauth2client.Table, sqlgraph.NewFieldSpec(oauth2client.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(oauth2client.FieldSecret, field.TypeString, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.RedirectUris(); ok {
		_spec.SetField(oauth2client.FieldRedirectUris, field.TypeJSON, value)
		_node.RedirectUris = value
	}
	if value, ok := _c.mutation.TrustedPeers(); ok {
		_spec.SetField(oauth2client.FieldTrustedPeers, field.TypeJSON, value)
		_node.TrustedPeers = value
	}
	if value, ok := _c.mutation.Public(); ok {
		_spec.SetField(oauth2client.FieldPublic, field.TypeBool, value)
		_node.Public = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauth2client.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(oauth2client.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuth2Client.Create().
//		SetSecret(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuth2ClientUpsert) {
//			SetSecret(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuth2ClientCreate) OnConflict(opts ...sql.ConflictOption) *OAuth2ClientUpsertOne {
	_c.conflict = opts
	return &OAuth2ClientUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuth2ClientCreate) OnConflictColumns(columns ...string) *OAuth2ClientUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuth2ClientUpsertOne{
		create: _c,
	}
}

type (
	// OAuth2ClientUpsertOne is the builder for "upsert"-ing
	//  one OAuth2Client node.
	OAuth2ClientUpsertOne struct {
		create *OAuth2ClientCreate
	}

	// OAuth2ClientUpsert is the "OnConflict" setter.
	OAuth2ClientUpsert struct {
		*sql.UpdateSet
	}
)

// SetSecret sets the "secret" field.
func (u *OAuth2ClientUpsert) SetSecret(v string) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldSecret, v)
	return u
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdateSecret() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldSecret)
	return u
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuth2ClientUpsert) SetRedirectUris(v []string) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldRedirectUris, v)
	return u
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdateRedirectUris() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldRedirectUris)
	return u
}

// ClearRedirectUris clears the value of the "redirect_uris" field.
func (u *OAuth2ClientUpsert) ClearRedirectUris() *OAuth2ClientUpsert {
	u.SetNull(oauth2client.FieldRedirectUris)
	return u
}

// SetTrustedPeers sets the "trusted_peers" field.
func (u *OAuth2ClientUpsert) SetTrustedPeers(v []string) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldTrustedPeers, v)
	return u
}

// UpdateTrustedPeers sets the "trusted_peers" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdateTrustedPeers() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldTrustedPeers)
	return u
}

// ClearTrustedPeers clears the value of the "trusted_peers" field.
func (u *OAuth2ClientUpsert) ClearTrustedPeers() *OAuth2ClientUpsert {
	u.SetNull(oauth2client.FieldTrustedPeers)
	return u
}

// SetPublic sets the "public" field.
func (u *OAuth2ClientUpsert) SetPublic(v bool) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldPublic, v)
	return u
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdatePublic() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldPublic)
	return u
}

// SetName sets the "name" field.
func (u *OAuth2ClientUpsert) SetName(v string) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdateName() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldName)
	return u
}

// SetLogoURL sets the "logo_url" field.
func (u *OAuth2ClientUpsert) SetLogoURL(v string) *OAuth2ClientUpsert {
	u.Set(oauth2client.FieldLogoURL, v)
	return u
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *OAuth2ClientUpsert) UpdateLogoURL() *OAuth2ClientUpsert {
	u.SetExcluded(oauth2client.FieldLogoURL)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauth2client.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuth2ClientUpsertOne) UpdateNewValues() *OAuth2ClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oauth2client.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuth2ClientUpsertOne) Ignore() *OAuth2ClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuth2ClientUpsertOne) DoNothing() *OAuth2ClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuth2ClientCreate.OnConflict
// documentation for more info.
func (u *OAuth2ClientUpsertOne) Update(set func(*OAuth2ClientUpsert)) *OAuth2ClientUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuth2ClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetSecret sets the "secret" field.
func (u *OAuth2ClientUpsertOne) SetSecret(v string) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdateSecret() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateSecret()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuth2ClientUpsertOne) SetRedirectUris(v []string) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdateRedirectUris() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// ClearRedirectUris clears the value of the "redirect_uris" field.
func (u *OAuth2ClientUpsertOne) ClearRedirectUris() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.ClearRedirectUris()
	})
}

// SetTrustedPeers sets the "trusted_peers" field.
func (u *OAuth2ClientUpsertOne) SetTrustedPeers(v []string) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetTrustedPeers(v)
	})
}

// UpdateTrustedPeers sets the "trusted_peers" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdateTrustedPeers() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateTrustedPeers()
	})
}

// ClearTrustedPeers clears the value of the "trusted_peers" field.
func (u *OAuth2ClientUpsertOne) ClearTrustedPeers() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.ClearTrustedPeers()
	})
}

// SetPublic sets the "public" field.
func (u *OAuth2ClientUpsertOne) SetPublic(v bool) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetPublic(v)
	})
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdatePublic() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdatePublic()
	})
}

// SetName sets the "name" field.
func (u *OAuth2ClientUpsertOne) SetName(v string) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdateName() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateName()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *OAuth2ClientUpsertOne) SetLogoURL(v string) *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *OAuth2ClientUpsertOne) UpdateLogoURL() *OAuth2ClientUpsertOne {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateLogoURL()
	})
}

// Exec executes the query.
func (u *OAuth2ClientUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for OAuth2ClientCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuth2ClientUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuth2ClientUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: OAuth2ClientUpsertOne.ID is not supported by MySQL driver. Use OAuth2ClientUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuth2ClientUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuth2ClientCreateBulk is the builder for creating many OAuth2Client entities in bulk.
type OAuth2ClientCreateBulk struct {
	config
	err      error
	builders []*OAuth2ClientCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuth2Client entities in the database.
func (_c *OAuth2ClientCreateBulk) Save(ctx context.Context) ([]*OAuth2Client, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuth2Client, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuth2ClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuth2ClientCreateBulk) SaveX(ctx context.Context) []*OAuth2Client {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuth2ClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuth2ClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuth2Client.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuth2ClientUpsert) {
//			SetSecret(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuth2ClientCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuth2ClientUpsertBulk {
	_c.conflict = opts
	return &OAuth2ClientUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuth2ClientCreateBulk) OnConflictColumns(columns ...string) *OAuth2ClientUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuth2ClientUpsertBulk{
		create: _c,
	}
}

// OAuth2ClientUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuth2Client nodes.
type OAuth2ClientUpsertBulk struct {
	create *OAuth2ClientCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oauth2client.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OAuth2ClientUpsertBulk) UpdateNewValues() *OAuth2ClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oauth2client.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuth2Client.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuth2ClientUpsertBulk) Ignore() *OAuth2ClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuth2ClientUpsertBulk) DoNothing() *OAuth2ClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuth2ClientCreateBulk.OnConflict
// documentation for more info.
func (u *OAuth2ClientUpsertBulk) Update(set func(*OAuth2ClientUpsert)) *OAuth2ClientUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuth2ClientUpsert{UpdateSet: update})
	}))
	return u
}

// SetSecret sets the "secret" field.
func (u *OAuth2ClientUpsertBulk) SetSecret(v string) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetSecret(v)
	})
}

// UpdateSecret sets the "secret" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdateSecret() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateSecret()
	})
}

// SetRedirectUris sets the "redirect_uris" field.
func (u *OAuth2ClientUpsertBulk) SetRedirectUris(v []string) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetRedirectUris(v)
	})
}

// UpdateRedirectUris sets the "redirect_uris" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdateRedirectUris() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateRedirectUris()
	})
}

// ClearRedirectUris clears the value of the "redirect_uris" field.
func (u *OAuth2ClientUpsertBulk) ClearRedirectUris() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.ClearRedirectUris()
	})
}

// SetTrustedPeers sets the "trusted_peers" field.
func (u *OAuth2ClientUpsertBulk) SetTrustedPeers(v []string) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetTrustedPeers(v)
	})
}

// UpdateTrustedPeers sets the "trusted_peers" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdateTrustedPeers() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateTrustedPeers()
	})
}

// ClearTrustedPeers clears the value of the "trusted_peers" field.
func (u *OAuth2ClientUpsertBulk) ClearTrustedPeers() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.ClearTrustedPeers()
	})
}

// SetPublic sets the "public" field.
func (u *OAuth2ClientUpsertBulk) SetPublic(v bool) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetPublic(v)
	})
}

// UpdatePublic sets the "public" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdatePublic() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdatePublic()
	})
}

// SetName sets the "name" field.
func (u *OAuth2ClientUpsertBulk) SetName(v string) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdateName() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateName()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *OAuth2ClientUpsertBulk) SetLogoURL(v string) *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *OAuth2ClientUpsertBulk) UpdateLogoURL() *OAuth2ClientUpsertBulk {
	return u.Update(func(s *OAuth2ClientUpsert) {
		s.UpdateLogoURL()
	})
}

// Exec executes the query.
func (u *OAuth2ClientUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the OAuth2ClientCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for OAuth2ClientCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuth2ClientUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
