// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/offlinesession"
)

// OfflineSessionCreate is the builder for creating a OfflineSession entity.
type OfflineSessionCreate struct {
	config
	mutation *OfflineSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *OfflineSessionCreate) SetUserID(v string) *OfflineSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetConnID sets the "conn_id" field.
func (_c *OfflineSessionCreate) SetConnID(v string) *OfflineSessionCreate {
	_c.mutation.SetConnID(v)
	return _c
}

// SetRefresh sets the "refresh" field.
func (_c *OfflineSessionCreate) SetRefresh(v []byte) *OfflineSessionCreate {
	_c.mutation.SetRefresh(v)
	return _c
}

// SetConnectorData sets the "connector_data" field.
func (_c *OfflineSessionCreate) SetConnectorData(v []byte) *OfflineSessionCreate {
	_c.mutation.SetConnectorData(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OfflineSessionCreate) SetID(v string) *OfflineSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OfflineSessionMutation object of the builder.
func (_c *OfflineSessionCreate) Mutation() *OfflineSessionMutation {
	return _c.mutation
}

// Save creates the OfflineSession in the database.
func (_c *OfflineSessionCreate) Save(ctx context.Context) (*OfflineSession, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OfflineSessionCreate) SaveX(ctx context.Context) *OfflineSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OfflineSessionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`db: missing required field "OfflineSession.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := offlinesession.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`db: validator failed for field "OfflineSession.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConnID(); !ok {
		return &ValidationError{Name: "conn_id", err: errors.New(`db: missing required field "OfflineSession.conn_id"`)}
	}
	if v, ok := _c.mutation.ConnID(); ok {
		if err := offlinesession.ConnIDValidator(v); err != nil {
			return &ValidationError{Name: "conn_id", err: fmt.Errorf(`db: validator failed for field "OfflineSession.conn_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Refresh(); !ok {
		return &ValidationError{Name: "refresh", err: errors.New(`db: missing required field "OfflineSession.refresh"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := offlinesession.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`db: validator failed for field "OfflineSession.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OfflineSessionCreate) sqlSave(ctx context.Context) (*OfflineSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OfflineSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OfflineSessionCreate) createSpec() (*OfflineSession, *sqlgraph.CreateSpec) {
	var (
		_node = &OfflineSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(offlinesession.Table, sqlgraph.NewFieldSpec(offlinesession.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(offlinesession.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ConnID(); ok {
		_spec.SetField(offlinesession.FieldConnID, field.TypeString, value)
		_node.ConnID = value
	}
	if value, ok := _c.mutation.Refresh(); ok {
		_spec.SetField(offlinesession.FieldRefresh, field.TypeBytes, value)
		_node.Refresh = value
	}
	if value, ok := _c.mutation.ConnectorData(); ok {
		_spec.SetField(offlinesession.FieldConnectorData, field.TypeBytes, value)
		_node.ConnectorData = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OfflineSession.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OfflineSessionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *OfflineSessionCreate) OnConflict(opts ...sql.ConflictOption) *OfflineSessionUpsertOne {
	_c.conflict = opts
	return &OfflineSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OfflineSessionCreate) OnConflictColumns(columns ...string) *OfflineSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OfflineSessionUpsertOne{
		create: _c,
	}
}

type (
	// OfflineSessionUpsertOne is the builder for "upsert"-ing
	//  one OfflineSession node.
	OfflineSessionUpsertOne struct {
		create *OfflineSessionCreate
	}

	// OfflineSessionUpsert is the "OnConflict" setter.
	OfflineSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *OfflineSessionUpsert) SetUserID(v string) *OfflineSessionUpsert {
	u.Set(offlinesession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OfflineSessionUpsert) UpdateUserID() *OfflineSessionUpsert {
	u.SetExcluded(offlinesession.FieldUserID)
	return u
}

// SetConnID sets the "conn_id" field.
func (u *OfflineSessionUpsert) SetConnID(v string) *OfflineSessionUpsert {
	u.Set(offlinesession.FieldConnID, v)
	return u
}

// UpdateConnID sets the "conn_id" field to the value that was provided on create.
func (u *OfflineSessionUpsert) UpdateConnID() *OfflineSessionUpsert {
	u.SetExcluded(offlinesession.FieldConnID)
	return u
}

// SetRefresh sets the "refresh" field.
func (u *OfflineSessionUpsert) SetRefresh(v []byte) *OfflineSessionUpsert {
	u.Set(offlinesession.FieldRefresh, v)
	return u
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *OfflineSessionUpsert) UpdateRefresh() *OfflineSessionUpsert {
	u.SetExcluded(offlinesession.FieldRefresh)
	return u
}

// SetConnectorData sets the "connector_data" field.
func (u *OfflineSessionUpsert) SetConnectorData(v []byte) *OfflineSessionUpsert {
	u.Set(offlinesession.FieldConnectorData, v)
	return u
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *OfflineSessionUpsert) UpdateConnectorData() *OfflineSessionUpsert {
	u.SetExcluded(offlinesession.FieldConnectorData)
	return u
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *OfflineSessionUpsert) ClearConnectorData() *OfflineSessionUpsert {
	u.SetNull(offlinesession.FieldConnectorData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(offlinesession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OfflineSessionUpsertOne) UpdateNewValues() *OfflineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(offlinesession.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OfflineSessionUpsertOne) Ignore() *OfflineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OfflineSessionUpsertOne) DoNothing() *OfflineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OfflineSessionCreate.OnConflict
// documentation for more info.
func (u *OfflineSessionUpsertOne) Update(set func(*OfflineSessionUpsert)) *OfflineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OfflineSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OfflineSessionUpsertOne) SetUserID(v string) *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OfflineSessionUpsertOne) UpdateUserID() *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetConnID sets the "conn_id" field.
func (u *OfflineSessionUpsertOne) SetConnID(v string) *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetConnID(v)
	})
}

// UpdateConnID sets the "conn_id" field to the value that was provided on create.
func (u *OfflineSessionUpsertOne) UpdateConnID() *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateConnID()
	})
}

// SetRefresh sets the "refresh" field.
func (u *OfflineSessionUpsertOne) SetRefresh(v []byte) *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetRefresh(v)
	})
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *OfflineSessionUpsertOne) UpdateRefresh() *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateRefresh()
	})
}

// SetConnectorData sets the "connector_data" field.
func (u *OfflineSessionUpsertOne) SetConnectorData(v []byte) *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetConnectorData(v)
	})
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *OfflineSessionUpsertOne) UpdateConnectorData() *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateConnectorData()
	})
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *OfflineSessionUpsertOne) ClearConnectorData() *OfflineSessionUpsertOne {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.ClearConnectorData()
	})
}

// Exec executes the query.
func (u *OfflineSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for OfflineSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OfflineSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OfflineSessionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: OfflineSessionUpsertOne.ID is not supported by MySQL driver. Use OfflineSessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OfflineSessionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OfflineSessionCreateBulk is the builder for creating many OfflineSession entities in bulk.
type OfflineSessionCreateBulk struct {
	config
	err      error
	builders []*OfflineSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the OfflineSession entities in the database.
func (_c *OfflineSessionCreateBulk) Save(ctx context.Context) ([]*OfflineSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OfflineSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OfflineSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OfflineSessionCreateBulk) SaveX(ctx context.Context) []*OfflineSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OfflineSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OfflineSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OfflineSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OfflineSessionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *OfflineSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OfflineSessionUpsertBulk {
	_c.conflict = opts
	return &OfflineSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OfflineSessionCreateBulk) OnConflictColumns(columns ...string) *OfflineSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OfflineSessionUpsertBulk{
		create: _c,
	}
}

// OfflineSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of OfflineSession nodes.
type OfflineSessionUpsertBulk struct {
	create *OfflineSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(offlinesession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OfflineSessionUpsertBulk) UpdateNewValues() *OfflineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(offlinesession.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OfflineSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OfflineSessionUpsertBulk) Ignore() *OfflineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OfflineSessionUpsertBulk) DoNothing() *OfflineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OfflineSessionCreateBulk.OnConflict
// documentation for more info.
func (u *OfflineSessionUpsertBulk) Update(set func(*OfflineSessionUpsert)) *OfflineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OfflineSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *OfflineSessionUpsertBulk) SetUserID(v string) *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OfflineSessionUpsertBulk) UpdateUserID() *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetConnID sets the "conn_id" field.
func (u *OfflineSessionUpsertBulk) SetConnID(v string) *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetConnID(v)
	})
}

// UpdateConnID sets the "conn_id" field to the value that was provided on create.
func (u *OfflineSessionUpsertBulk) UpdateConnID() *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateConnID()
	})
}

// SetRefresh sets the "refresh" field.
func (u *OfflineSessionUpsertBulk) SetRefresh(v []byte) *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetRefresh(v)
	})
}

// UpdateRefresh sets the "refresh" field to the value that was provided on create.
func (u *OfflineSessionUpsertBulk) UpdateRefresh() *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateRefresh()
	})
}

// SetConnectorData sets the "connector_data" field.
func (u *OfflineSessionUpsertBulk) SetConnectorData(v []byte) *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.SetConnectorData(v)
	})
}

// UpdateConnectorData sets the "connector_data" field to the value that was provided on create.
func (u *OfflineSessionUpsertBulk) UpdateConnectorData() *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.UpdateConnectorData()
	})
}

// ClearConnectorData clears the value of the "connector_data" field.
func (u *OfflineSessionUpsertBulk) ClearConnectorData() *OfflineSessionUpsertBulk {
	return u.Update(func(s *OfflineSessionUpsert) {
		s.ClearConnectorData()
	})
}

// Exec executes the query.
func (u *OfflineSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the OfflineSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for OfflineSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OfflineSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
