// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/signuptoken"
)

// SignupTokenCreate is the builder for creating a SignupToken entity.
type SignupTokenCreate struct {
	config
	mutation *SignupTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEmail sets the "email" field.
func (_c *SignupTokenCreate) SetEmail(v string) *SignupTokenCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCsrfToken sets the "csrf_token" field.
func (_c *SignupTokenCreate) SetCsrfToken(v string) *SignupTokenCreate {
	_c.mutation.SetCsrfToken(v)
	return _c
}

// SetValidationToken sets the "validation_token" field.
func (_c *SignupTokenCreate) SetValidationToken(v string) *SignupTokenCreate {
	_c.mutation.SetValidationToken(v)
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *SignupTokenCreate) SetExpiry(v time.Time) *SignupTokenCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// Mutation returns the SignupTokenMutation object of the builder.
func (_c *SignupTokenCreate) Mutation() *SignupTokenMutation {
	return _c.mutation
}

// Save creates the SignupToken in the database.
func (_c *SignupTokenCreate) Save(ctx context.Context) (*SignupToken, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SignupTokenCreate) SaveX(ctx context.Context) *SignupToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignupTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignupTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SignupTokenCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`db: missing required field "SignupToken.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := signuptoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`db: validator failed for field "SignupToken.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CsrfToken(); !ok {
		return &ValidationError{Name: "csrf_token", err: errors.New(`db: missing required field "SignupToken.csrf_token"`)}
	}
	if v, ok := _c.mutation.CsrfToken(); ok {
		if err := signuptoken.CsrfTokenValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.csrf_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidationToken(); !ok {
		return &ValidationError{Name: "validation_token", err: errors.New(`db: missing required field "SignupToken.validation_token"`)}
	}
	if v, ok := _c.mutation.ValidationToken(); ok {
		if err := signuptoken.ValidationTokenValidator(v); err != nil {
			return &ValidationError{Name: "validation_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.validation_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`db: missing required field "SignupToken.expiry"`)}
	}
	return nil
}

func (_c *SignupTokenCreate) sqlSave(ctx context.Context) (*SignupToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SignupTokenCreate) createSpec() (*SignupToken, *sqlgraph.CreateSpec) {
	var (
		_node = &SignupToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signuptoken.Table, sqlgraph.NewFieldSpec(signuptoken.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(signuptoken.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CsrfToken(); ok {
		_spec.SetField(signuptoken.FieldCsrfToken, field.TypeString, value)
		_node.CsrfToken = value
	}
	if value, ok := _c.mutation.ValidationToken(); ok {
		_spec.SetField(signuptoken.FieldValidationToken, field.TypeString, value)
		_node.ValidationToken = value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(signuptoken.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SignupToken.Create().
//		SetEmail(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignupTokenUpsert) {
//			SetEmail(v+v).
//		}).
//		Exec(ctx)
func (_c *SignupTokenCreate) OnConflict(opts ...sql.ConflictOption) *SignupTokenUpsertOne {
	_c.conflict = opts
	return &SignupTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignupTokenCreate) OnConflictColumns(columns ...string) *SignupTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignupTokenUpsertOne{
		create: _c,
	}
}

type (
	// SignupTokenUpsertOne is the builder for "upsert"-ing
	//  one SignupToken node.
	SignupTokenUpsertOne struct {
		create *SignupTokenCreate
	}

	// SignupTokenUpsert is the "OnConflict" setter.
	SignupTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetEmail sets the "email" field.
func (u *SignupTokenUpsert) SetEmail(v string) *SignupTokenUpsert {
	u.Set(signuptoken.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SignupTokenUpsert) UpdateEmail() *SignupTokenUpsert {
	u.SetExcluded(signuptoken.FieldEmail)
	return u
}

// SetCsrfToken sets the "csrf_token" field.
func (u *SignupTokenUpsert) SetCsrfToken(v string) *SignupTokenUpsert {
	u.Set(signuptoken.FieldCsrfToken, v)
	return u
}

// UpdateCsrfToken sets the "csrf_token" field to the value that was provided on create.
func (u *SignupTokenUpsert) UpdateCsrfToken() *SignupTokenUpsert {
	u.SetExcluded(signuptoken.FieldCsrfToken)
	return u
}

// SetValidationToken sets the "validation_token" field.
func (u *SignupTokenUpsert) SetValidationToken(v string) *SignupTokenUpsert {
	u.Set(signuptoken.FieldValidationToken, v)
	return u
}

// UpdateValidationToken sets the "validation_token" field to the value that was provided on create.
func (u *SignupTokenUpsert) UpdateValidationToken() *SignupTokenUpsert {
	u.SetExcluded(signuptoken.FieldValidationToken)
	return u
}

// SetExpiry sets the "expiry" field.
func (u *SignupTokenUpsert) SetExpiry(v time.Time) *SignupTokenUpsert {
	u.Set(signuptoken.FieldExpiry, v)
	return u
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *SignupTokenUpsert) UpdateExpiry() *SignupTokenUpsert {
	u.SetExcluded(signuptoken.FieldExpiry)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignupTokenUpsertOne) UpdateNewValues() *SignupTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SignupTokenUpsertOne) Ignore() *SignupTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignupTokenUpsertOne) DoNothing() *SignupTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignupTokenCreate.OnConflict
// documentation for more info.
func (u *SignupTokenUpsertOne) Update(set func(*SignupTokenUpsert)) *SignupTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignupTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmail sets the "email" field.
func (u *SignupTokenUpsertOne) SetEmail(v string) *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SignupTokenUpsertOne) UpdateEmail() *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateEmail()
	})
}

// SetCsrfToken sets the "csrf_token" field.
func (u *SignupTokenUpsertOne) SetCsrfToken(v string) *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetCsrfToken(v)
	})
}

// UpdateCsrfToken sets the "csrf_token" field to the value that was provided on create.
func (u *SignupTokenUpsertOne) UpdateCsrfToken() *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateCsrfToken()
	})
}

// SetValidationToken sets the "validation_token" field.
func (u *SignupTokenUpsertOne) SetValidationToken(v string) *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetValidationToken(v)
	})
}

// UpdateValidationToken sets the "validation_token" field to the value that was provided on create.
func (u *SignupTokenUpsertOne) UpdateValidationToken() *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateValidationToken()
	})
}

// SetExpiry sets the "expiry" field.
func (u *SignupTokenUpsertOne) SetExpiry(v time.Time) *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetExpiry(v)
	})
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *SignupTokenUpsertOne) UpdateExpiry() *SignupTokenUpsertOne {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateExpiry()
	})
}

// Exec executes the query.
func (u *SignupTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for SignupTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignupTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SignupTokenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SignupTokenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SignupTokenCreateBulk is the builder for creating many SignupToken entities in bulk.
type SignupTokenCreateBulk struct {
	config
	err      error
	builders []*SignupTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the SignupToken entities in the database.
func (_c *SignupTokenCreateBulk) Save(ctx context.Context) ([]*SignupToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SignupToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignupTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SignupTokenCreateBulk) SaveX(ctx context.Context) []*SignupToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignupTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignupTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SignupToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignupTokenUpsert) {
//			SetEmail(v+v).
//		}).
//		Exec(ctx)
func (_c *SignupTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *SignupTokenUpsertBulk {
	_c.conflict = opts
	return &SignupTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignupTokenCreateBulk) OnConflictColumns(columns ...string) *SignupTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignupTokenUpsertBulk{
		create: _c,
	}
}

// SignupTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of SignupToken nodes.
type SignupTokenUpsertBulk struct {
	create *SignupTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignupTokenUpsertBulk) UpdateNewValues() *SignupTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SignupToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SignupTokenUpsertBulk) Ignore() *SignupTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignupTokenUpsertBulk) DoNothing() *SignupTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignupTokenCreateBulk.OnConflict
// documentation for more info.
func (u *SignupTokenUpsertBulk) Update(set func(*SignupTokenUpsert)) *SignupTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignupTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmail sets the "email" field.
func (u *SignupTokenUpsertBulk) SetEmail(v string) *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *SignupTokenUpsertBulk) UpdateEmail() *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateEmail()
	})
}

// SetCsrfToken sets the "csrf_token" field.
func (u *SignupTokenUpsertBulk) SetCsrfToken(v string) *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetCsrfToken(v)
	})
}

// UpdateCsrfToken sets the "csrf_token" field to the value that was provided on create.
func (u *SignupTokenUpsertBulk) UpdateCsrfToken() *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateCsrfToken()
	})
}

// SetValidationToken sets the "validation_token" field.
func (u *SignupTokenUpsertBulk) SetValidationToken(v string) *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetValidationToken(v)
	})
}

// UpdateValidationToken sets the "validation_token" field to the value that was provided on create.
func (u *SignupTokenUpsertBulk) UpdateValidationToken() *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateValidationToken()
	})
}

// SetExpiry sets the "expiry" field.
func (u *SignupTokenUpsertBulk) SetExpiry(v time.Time) *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.SetExpiry(v)
	})
}

// UpdateExpiry sets the "expiry" field to the value that was provided on create.
func (u *SignupTokenUpsertBulk) UpdateExpiry() *SignupTokenUpsertBulk {
	return u.Update(func(s *SignupTokenUpsert) {
		s.UpdateExpiry()
	})
}

// Exec executes the query.
func (u *SignupTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the SignupTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for SignupTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignupTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
