// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/predicate"
	"github.com/dexidp/dex/storage/ent/db/signuptoken"
)

// SignupTokenUpdate is the builder for updating SignupToken entities.
type SignupTokenUpdate struct {
	config
	hooks    []Hook
	mutation *SignupTokenMutation
}

// Where appends a list predicates to the SignupTokenUpdate builder.
func (_u *SignupTokenUpdate) Where(ps ...predicate.SignupToken) *SignupTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *SignupTokenUpdate) SetEmail(v string) *SignupTokenUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SignupTokenUpdate) SetNillableEmail(v *string) *SignupTokenUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCsrfToken sets the "csrf_token" field.
func (_u *SignupTokenUpdate) SetCsrfToken(v string) *SignupTokenUpdate {
	_u.mutation.SetCsrfToken(v)
	return _u
}

// SetNillableCsrfToken sets the "csrf_token" field if the given value is not nil.
func (_u *SignupTokenUpdate) SetNillableCsrfToken(v *string) *SignupTokenUpdate {
	if v != nil {
		_u.SetCsrfToken(*v)
	}
	return _u
}

// SetValidationToken sets the "validation_token" field.
func (_u *SignupTokenUpdate) SetValidationToken(v string) *SignupTokenUpdate {
	_u.mutation.SetValidationToken(v)
	return _u
}

// SetNillableValidationToken sets the "validation_token" field if the given value is not nil.
func (_u *SignupTokenUpdate) SetNillableValidationToken(v *string) *SignupTokenUpdate {
	if v != nil {
		_u.SetValidationToken(*v)
	}
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *SignupTokenUpdate) SetExpiry(v time.Time) *SignupTokenUpdate {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *SignupTokenUpdate) SetNillableExpiry(v *time.Time) *SignupTokenUpdate {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// Mutation returns the SignupTokenMutation object of the builder.
func (_u *SignupTokenUpdate) Mutation() *SignupTokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SignupTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignupTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SignupTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignupTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignupTokenUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := signuptoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`db: validator failed for field "SignupToken.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CsrfToken(); ok {
		if err := signuptoken.CsrfTokenValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.csrf_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationToken(); ok {
		if err := signuptoken.ValidationTokenValidator(v); err != nil {
			return &ValidationError{Name: "validation_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.validation_token": %w`, err)}
		}
	}
	return nil
}

func (_u *SignupTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signuptoken.Table, signuptoken.Columns, sqlgraph.NewFieldSpec(signuptoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(signuptoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfToken(); ok {
		_spec.SetField(signuptoken.FieldCsrfToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationToken(); ok {
		_spec.SetField(signuptoken.FieldValidationToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(signuptoken.FieldExpiry, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signuptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SignupTokenUpdateOne is the builder for updating a single SignupToken entity.
type SignupTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignupTokenMutation
}

// SetEmail sets the "email" field.
func (_u *SignupTokenUpdateOne) SetEmail(v string) *SignupTokenUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SignupTokenUpdateOne) SetNillableEmail(v *string) *SignupTokenUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCsrfToken sets the "csrf_token" field.
func (_u *SignupTokenUpdateOne) SetCsrfToken(v string) *SignupTokenUpdateOne {
	_u.mutation.SetCsrfToken(v)
	return _u
}

// SetNillableCsrfToken sets the "csrf_token" field if the given value is not nil.
func (_u *SignupTokenUpdateOne) SetNillableCsrfToken(v *string) *SignupTokenUpdateOne {
	if v != nil {
		_u.SetCsrfToken(*v)
	}
	return _u
}

// SetValidationToken sets the "validation_token" field.
func (_u *SignupTokenUpdateOne) SetValidationToken(v string) *SignupTokenUpdateOne {
	_u.mutation.SetValidationToken(v)
	return _u
}

// SetNillableValidationToken sets the "validation_token" field if the given value is not nil.
func (_u *SignupTokenUpdateOne) SetNillableValidationToken(v *string) *SignupTokenUpdateOne {
	if v != nil {
		_u.SetValidationToken(*v)
	}
	return _u
}

// SetExpiry sets the "expiry" field.
func (_u *SignupTokenUpdateOne) SetExpiry(v time.Time) *SignupTokenUpdateOne {
	_u.mutation.SetExpiry(v)
	return _u
}

// SetNillableExpiry sets the "expiry" field if the given value is not nil.
func (_u *SignupTokenUpdateOne) SetNillableExpiry(v *time.Time) *SignupTokenUpdateOne {
	if v != nil {
		_u.SetExpiry(*v)
	}
	return _u
}

// Mutation returns the SignupTokenMutation object of the builder.
func (_u *SignupTokenUpdateOne) Mutation() *SignupTokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the SignupTokenUpdate builder.
func (_u *SignupTokenUpdateOne) Where(ps ...predicate.SignupToken) *SignupTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SignupTokenUpdateOne) Select(field string, fields ...string) *SignupTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SignupToken entity.
func (_u *SignupTokenUpdateOne) Save(ctx context.Context) (*SignupToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignupTokenUpdateOne) SaveX(ctx context.Context) *SignupToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SignupTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignupTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SignupTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := signuptoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`db: validator failed for field "SignupToken.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CsrfToken(); ok {
		if err := signuptoken.CsrfTokenValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.csrf_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationToken(); ok {
		if err := signuptoken.ValidationTokenValidator(v); err != nil {
			return &ValidationError{Name: "validation_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.validation_token": %w`, err)}
		}
	}
	return nil
}

func (_u *SignupTokenUpdateOne) sqlSave(ctx context.Context) (_node *SignupToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(signuptoken.Table, signuptoken.Columns, sqlgraph.NewFieldSpec(signuptoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "SignupToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signuptoken.FieldID)
		for _, f := range fields {
			if !signuptoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != signuptoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(signuptoken.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CsrfToken(); ok {
		_spec.SetField(signuptoken.FieldCsrfToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationToken(); ok {
		_spec.SetField(signuptoken.FieldValidationToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expiry(); ok {
		_spec.SetField(signuptoken.FieldExpiry, field.TypeTime, value)
	}
	_node = &SignupToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signuptoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
