// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dexidp/dex/storage/ent/db/signuptoken"
)

// SignupTokenCreate is the builder for creating a SignupToken entity.
type SignupTokenCreate struct {
	config
	mutation *SignupTokenMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *SignupTokenCreate) SetEmail(v string) *SignupTokenCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCsrfToken sets the "csrf_token" field.
func (_c *SignupTokenCreate) SetCsrfToken(v string) *SignupTokenCreate {
	_c.mutation.SetCsrfToken(v)
	return _c
}

// SetValidationToken sets the "validation_token" field.
func (_c *SignupTokenCreate) SetValidationToken(v string) *SignupTokenCreate {
	_c.mutation.SetValidationToken(v)
	return _c
}

// SetExpiry sets the "expiry" field.
func (_c *SignupTokenCreate) SetExpiry(v time.Time) *SignupTokenCreate {
	_c.mutation.SetExpiry(v)
	return _c
}

// Mutation returns the SignupTokenMutation object of the builder.
func (_c *SignupTokenCreate) Mutation() *SignupTokenMutation {
	return _c.mutation
}

// Save creates the SignupToken in the database.
func (_c *SignupTokenCreate) Save(ctx context.Context) (*SignupToken, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SignupTokenCreate) SaveX(ctx context.Context) *SignupToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignupTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignupTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SignupTokenCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`db: missing required field "SignupToken.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := signuptoken.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`db: validator failed for field "SignupToken.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CsrfToken(); !ok {
		return &ValidationError{Name: "csrf_token", err: errors.New(`db: missing required field "SignupToken.csrf_token"`)}
	}
	if v, ok := _c.mutation.CsrfToken(); ok {
		if err := signuptoken.CsrfTokenValidator(v); err != nil {
			return &ValidationError{Name: "csrf_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.csrf_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidationToken(); !ok {
		return &ValidationError{Name: "validation_token", err: errors.New(`db: missing required field "SignupToken.validation_token"`)}
	}
	if v, ok := _c.mutation.ValidationToken(); ok {
		if err := signuptoken.ValidationTokenValidator(v); err != nil {
			return &ValidationError{Name: "validation_token", err: fmt.Errorf(`db: validator failed for field "SignupToken.validation_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expiry(); !ok {
		return &ValidationError{Name: "expiry", err: errors.New(`db: missing required field "SignupToken.expiry"`)}
	}
	return nil
}

func (_c *SignupTokenCreate) sqlSave(ctx context.Context) (*SignupToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SignupTokenCreate) createSpec() (*SignupToken, *sqlgraph.CreateSpec) {
	var (
		_node = &SignupToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signuptoken.Table, sqlgraph.NewFieldSpec(signuptoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(signuptoken.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CsrfToken(); ok {
		_spec.SetField(signuptoken.FieldCsrfToken, field.TypeString, value)
		_node.CsrfToken = value
	}
	if value, ok := _c.mutation.ValidationToken(); ok {
		_spec.SetField(signuptoken.FieldValidationToken, field.TypeString, value)
		_node.ValidationToken = value
	}
	if value, ok := _c.mutation.Expiry(); ok {
		_spec.SetField(signuptoken.FieldExpiry, field.TypeTime, value)
		_node.Expiry = value
	}
	return _node, _spec
}

// SignupTokenCreateBulk is the builder for creating many SignupToken entities in bulk.
type SignupTokenCreateBulk struct {
	config
	err      error
	builders []*SignupTokenCreate
}

// Save creates the SignupToken entities in the database.
func (_c *SignupTokenCreateBulk) Save(ctx context.Context) ([]*SignupToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SignupToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignupTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SignupTokenCreateBulk) SaveX(ctx context.Context) []*SignupToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignupTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignupTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
