// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dexidp/dex/storage/ent/db/signuptoken"
)

// SignupToken is the model entity for the SignupToken schema.
type SignupToken struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CsrfToken holds the value of the "csrf_token" field.
	CsrfToken string `json:"csrf_token,omitempty"`
	// ValidationToken holds the value of the "validation_token" field.
	ValidationToken string `json:"validation_token,omitempty"`
	// Expiry holds the value of the "expiry" field.
	Expiry       time.Time `json:"expiry,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SignupToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case signuptoken.FieldID:
			values[i] = new(sql.NullInt64)
		case signuptoken.FieldEmail, signuptoken.FieldCsrfToken, signuptoken.FieldValidationToken:
			values[i] = new(sql.NullString)
		case signuptoken.FieldExpiry:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SignupToken fields.
func (_m *SignupToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case signuptoken.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case signuptoken.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case signuptoken.FieldCsrfToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field csrf_token", values[i])
			} else if value.Valid {
				_m.CsrfToken = value.String
			}
		case signuptoken.FieldValidationToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field validation_token", values[i])
			} else if value.Valid {
				_m.ValidationToken = value.String
			}
		case signuptoken.FieldExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry", values[i])
			} else if value.Valid {
				_m.Expiry = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SignupToken.
// This includes values selected through modifiers, order, etc.
func (_m *SignupToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SignupToken.
// Note that you need to call SignupToken.Unwrap() before calling this method if this SignupToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SignupToken) Update() *SignupTokenUpdateOne {
	return NewSignupTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SignupToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SignupToken) Unwrap() *SignupToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: SignupToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SignupToken) String() string {
	var builder strings.Builder
	builder.WriteString("SignupToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("csrf_token=")
	builder.WriteString(_m.CsrfToken)
	builder.WriteString(", ")
	builder.WriteString("validation_token=")
	builder.WriteString(_m.ValidationToken)
	builder.WriteString(", ")
	builder.WriteString("expiry=")
	builder.WriteString(_m.Expiry.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SignupTokens is a parsable slice of SignupToken.
type SignupTokens []*SignupToken
